// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace eSusInsurers.Domain.Models.Configurations
{
    public partial class InsuranceProviderConfiguration : IEntityTypeConfiguration<InsuranceProvider>
    {
        public void Configure(EntityTypeBuilder<InsuranceProvider> entity)
        {
            entity.Property(e => e.Id).HasColumnName("InsurerId");
            entity.HasKey(e => e.Id).HasName("PK__eSusInsu__7E508CE6AF228DD5");

            entity.Property(e => e.Address).IsUnicode(false);
            entity.Property(e => e.Comments).IsUnicode(false);
            entity.Property(e => e.ContactNumber1).HasColumnType("numeric(15, 0)");
            entity.Property(e => e.ContactNumber2).HasColumnType("numeric(15, 0)");
            entity.Property(e => e.ContactPersonAlternateContactNumber).HasColumnType("numeric(15, 0)");
            entity.Property(e => e.ContactPersonAlternateEmailId)
            .HasMaxLength(300)
            .IsUnicode(false);
            entity.Property(e => e.ContactPersonEmailId)
            .IsRequired()
            .HasMaxLength(300)
            .IsUnicode(false);
            entity.Property(e => e.ContactPersonMobileNumber).HasColumnType("numeric(15, 0)");
            entity.Property(e => e.ContactPersonName)
            .IsRequired()
            .HasMaxLength(200)
            .IsUnicode(false);
            entity.Property(e => e.Country)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.EmailId1)
            .IsRequired()
            .HasMaxLength(300)
            .IsUnicode(false);
            entity.Property(e => e.EmailId2)
            .HasMaxLength(300)
            .IsUnicode(false);
            entity.Property(e => e.HeadOfficeAddress)
            .IsRequired()
            .HasMaxLength(300)
            .IsUnicode(false);
            entity.Property(e => e.InsurerName)
            .IsRequired()
            .HasMaxLength(200)
            .IsUnicode(false);
            entity.Property(e => e.IsEnforcePassword).HasDefaultValue(true);
            entity.Property(e => e.LastVersion)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.Latitude).HasColumnType("decimal(8, 6)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.ModifiedBy)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Password).IsUnicode(false);
            entity.Property(e => e.ProfilePicture)
            .HasMaxLength(250)
            .IsUnicode(false);
            entity.Property(e => e.Status)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.TaxIdentificationNumber)
            .HasMaxLength(100)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InsuranceProvider> entity);
    }
}
