// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using eSusInsurers.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
#nullable disable

namespace eSusInsurers.Domain.Models;

public partial class esusinsurer_nonprodContext : DbContext
{
    public esusinsurer_nonprodContext(DbContextOptions<esusinsurer_nonprodContext> options)
        : base(options)
    {
    }

    public virtual DbSet<InsuranceProvider> InsuranceProviders { get; set; }

    public virtual DbSet<InsuranceProviderDocument> InsuranceProviderDocuments { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.InsuranceProviderConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.InsuranceProviderDocumentConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

}
